import React from 'react'
import { Avatar, Box, Button, CardHeader, Grid, Stack, Typography } from '@mui/material';
import { useRouter } from 'next/router';
import general_styles from '@/styles/General.module.css';
import Head from 'next/head';
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });
const ImageDetails = () => {
  const router = useRouter();
  const detailsData = router.query;
  
  return (
    <>
      <Head>
        <title>Next Images Gallery - Photo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`} id="home_page">
        <Stack className={`${general_styles.photo_stack}`}>
          <Grid container item xs={12} p={0} m={0} className={`${general_styles.page_head}`}>
            <Button className={`${general_styles.head_text}`}
              sx={{ padding: '0px !important' }}
              onClick={()=> {
                router.push({
                  pathname: `/`
                })
                }}          
            >Next Images Gallery</Button>
          </Grid>

          <Box mb={{ xs: '0rem', md: '3rem' }}>
            <CardHeader
              className={general_styles.user_avatar}
              avatar={
                <Avatar sx={{ width: "48px", height: "48px" }} aria-label="recipe" src={detailsData?.user_avatar} />
              }
              title={detailsData?.user_name}
              subheader={`${detailsData?.user_total_photos} photos`}
              titleTypographyProps={{
                sx:{
                  color: "#0d0c22",
                  fontWeight: "600",
                  fontSize: "14px"
                }
              }}
              subheaderTypographyProps={{
                sx:{
                  color: "#6e6d7a",
                  fontWeight: "500",
                  fontSize: "12px"
                }            
              }}
            />
          </Box>

          <Grid container p={0} m={0}>
            <Grid item xs={12} md={6} p={0} m={0}>
              <img
                src={detailsData?.src}
                className={`${general_styles.photo_stack_img}`}
              />
            </Grid>
            <Grid item xs={12} md={6} p={0} m={0}>
              <Typography component={'p'} className={general_styles.photo_stack_text}>
                <Typography component={'span'} className={general_styles.photo_stack_text_bold}>Image id: </Typography>{detailsData?.id}
              </Typography>
              <Typography component={'p'} className={general_styles.photo_stack_text}>
                <Typography component={'span'} className={general_styles.photo_stack_text_bold}>Description: </Typography>{detailsData?.slug}
              </Typography>
              <Typography component={'p'} className={general_styles.photo_stack_text}>
                <Typography component={'span'} className={general_styles.photo_stack_text_bold}>Width: </Typography>{detailsData?.width}
              </Typography>
              <Typography component={'p'} className={general_styles.photo_stack_text}>
                <Typography component={'span'} className={general_styles.photo_stack_text_bold}>Height: </Typography>{detailsData?.height}
              </Typography>
            </Grid>
          </Grid>
        </Stack>
      </main>
    </>
  )
}

export default ImageDetails